// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func SignupForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form class=\"bg-neutral-700 rounded-2xl bg-gray-600 backdrop-filter backdrop-blur-sm bg-opacity-10 p-5 space-y-2\" action=\"/api/signup\" method=\"post\"><div class=\"dark:text-neutral-200 font-bold\">SIGNUP</div><label for=\"username\" class=\"dark:text-neutral-300 text-xs\">Enter your username</label> <input id=\"username\" class=\"w-full border focus:border-2 rounded p-2 focus:outline-none focus:ring-0 text-neutral-200 placeholder:text-neutral-500\" placeholder=\"eg: JohnDoe69\"> <label for=\"password\" class=\"dark:text-neutral-300 text-xs\">Enter your password</label> <input id=\"password\" class=\"w-full border focus:border-2 rounded p-2 focus:outline-none focus:ring-0 text-neutral-200 placeholder:text-neutral-500\" placeholder=\"eg: Oax;I)\"> <button type=\"submit\" class=\"bg-neutral-300 hover:bg-neutral-50 w-full rounded text-center p-2 cursor-pointer\">Submit</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
