// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Credential struct {
	CredentialID          int32
	VaultItemID           int32
	Encryptedcredname     string
	Encryptedcredpassword string
}

type User struct {
	Userid             int32
	Username           string
	MasterPasswordHash string
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	SessionToken       sql.NullString
}

type Vault struct {
	VaultID                int32
	Userid                 int32
	VaultItemNameEncrypted string
}

type VaultItem struct {
	VaultItemID            int32
	VaultID                int32
	VaultItemNameEncrypted string
}
